# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DcWalrus < Formula
  desc "Dcycle CLI (Go rewrite)"
  homepage "https://github.com/Dcycle-by-WUM/dcycle-backend-app/tree/main/dc-go"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dcycle-by-WUM/dc-walrus-releases/releases/download/v0.0.8/dc-walrus_0.0.8_darwin_amd64.tar.gz"
      sha256 "c620a72cc7e3d7013306ec763c2b585c395fe627d2426fd69623fbdaa7f1abc9"

      define_method(:install) do
        bin.install "dc-walrus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dcycle-by-WUM/dc-walrus-releases/releases/download/v0.0.8/dc-walrus_0.0.8_darwin_arm64.tar.gz"
      sha256 "2548cc702b26b9a322ade8cbc86f4a4fd24f5a3099d242591a1b1f5299069e97"

      define_method(:install) do
        bin.install "dc-walrus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dcycle-by-WUM/dc-walrus-releases/releases/download/v0.0.8/dc-walrus_0.0.8_linux_amd64.tar.gz"
      sha256 "32d77a5cc631aabe813c91fb0799dc06b8ae0982dfe952e52fc1c1d1682db661"
      define_method(:install) do
        bin.install "dc-walrus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dcycle-by-WUM/dc-walrus-releases/releases/download/v0.0.8/dc-walrus_0.0.8_linux_arm64.tar.gz"
      sha256 "4e91105baad8343cd9bb6fcbf71793cdc278ba78d96646ae19946abbf635e938"
      define_method(:install) do
        bin.install "dc-walrus"
      end
    end
  end
end
