# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DcWalrus < Formula
  desc "Dcycle CLI (Go rewrite)"
  homepage "https://github.com/Dcycle-by-WUM/dcycle-backend-app/tree/main/dc-go"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dcycle-by-WUM/dcycle-backend-app/releases/download/v0.0.1/dc-walrus_0.0.1_darwin_amd64.tar.gz"
      sha256 "4806afe3cc09d261c813be558db83e22d89cf3854cf645e325331079dd11d06a"

      define_method(:install) do
        bin.install "dc-walrus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dcycle-by-WUM/dcycle-backend-app/releases/download/v0.0.1/dc-walrus_0.0.1_darwin_arm64.tar.gz"
      sha256 "8b4084334dc4ab5b69fbff4e6de3e5971582d8a14b2ba41e15ce77b385f56cf4"

      define_method(:install) do
        bin.install "dc-walrus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dcycle-by-WUM/dcycle-backend-app/releases/download/v0.0.1/dc-walrus_0.0.1_linux_amd64.tar.gz"
      sha256 "c24e682e3d838d03f5a60d98c67184091744db1a76c99700fc4ab97bb43f0fac"
      define_method(:install) do
        bin.install "dc-walrus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dcycle-by-WUM/dcycle-backend-app/releases/download/v0.0.1/dc-walrus_0.0.1_linux_arm64.tar.gz"
      sha256 "6888161321abdc6cd698ae47d76eb6d83508139ed1c7e1d6d9a2b2356472acd0"
      define_method(:install) do
        bin.install "dc-walrus"
      end
    end
  end
end
