# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DcWalrus < Formula
  desc "Dcycle CLI (Go rewrite)"
  homepage "https://github.com/Dcycle-by-WUM/dcycle-backend-app/tree/main/dc-go"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dcycle-by-WUM/dc-walrus-releases/releases/download/v0.0.1/dc-walrus_0.0.1_darwin_amd64.tar.gz"
      sha256 "47d6963d2f352d31d8e4dd8da67bc44a7ed511e8ce3d55020439af02baf07342"

      define_method(:install) do
        bin.install "dc-walrus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dcycle-by-WUM/dc-walrus-releases/releases/download/v0.0.1/dc-walrus_0.0.1_darwin_arm64.tar.gz"
      sha256 "d31959ee600543eb6a035d30ffa061d9b7da5e9fc1903532286e72091f77686f"

      define_method(:install) do
        bin.install "dc-walrus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dcycle-by-WUM/dc-walrus-releases/releases/download/v0.0.1/dc-walrus_0.0.1_linux_amd64.tar.gz"
      sha256 "afb26cbe16f3cbe868091d653dff375bde60a8a43bb9993d963b1ef550ecce69"
      define_method(:install) do
        bin.install "dc-walrus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dcycle-by-WUM/dc-walrus-releases/releases/download/v0.0.1/dc-walrus_0.0.1_linux_arm64.tar.gz"
      sha256 "dc25063fcfe79a8a90e585a701470e6db5ed3864ea29c1b31aba0e8107a0adbe"
      define_method(:install) do
        bin.install "dc-walrus"
      end
    end
  end
end
