# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dcy < Formula
  desc "Dcycle CLI"
  homepage "https://github.com/Dcycle-by-WUM/dcycle-backend-app/tree/main/dc-go"
  version "0.0.73"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dcycle-by-WUM/dcy-releases/releases/download/v0.0.73/dcy_0.0.73_darwin_amd64.tar.gz"
      sha256 "f518fca98bc62333b7f5c4075306b874e9ce20788b16236fc41fe40849f9dffc"

      define_method(:install) do
        bin.install "dcy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dcycle-by-WUM/dcy-releases/releases/download/v0.0.73/dcy_0.0.73_darwin_arm64.tar.gz"
      sha256 "f8092cae586fc7e74b82dded6e37d7d4cceaa208921db498479cb92ecd4e7491"

      define_method(:install) do
        bin.install "dcy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dcycle-by-WUM/dcy-releases/releases/download/v0.0.73/dcy_0.0.73_linux_amd64.tar.gz"
      sha256 "d8bfdb3d8192edd4720027f71e51b78e7c1728c52b81faeb2113b8a3b9fd859c"
      define_method(:install) do
        bin.install "dcy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dcycle-by-WUM/dcy-releases/releases/download/v0.0.73/dcy_0.0.73_linux_arm64.tar.gz"
      sha256 "71f4907390ccd8e2a36570fff919249678e6f47f31277e5b67bd199531d4d961"
      define_method(:install) do
        bin.install "dcy"
      end
    end
  end
end
