# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dcy < Formula
  desc "Dcycle CLI"
  homepage "https://github.com/Dcycle-by-WUM/dcycle-backend-app/tree/main/dc-go"
  version "0.0.77"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dcycle-by-WUM/dcy-releases/releases/download/v0.0.77/dcy_0.0.77_darwin_amd64.tar.gz"
      sha256 "c88cf1d1a300ad048d478a2167735257515626b2c7628aa0bfef29345c95f3bf"

      define_method(:install) do
        bin.install "dcy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dcycle-by-WUM/dcy-releases/releases/download/v0.0.77/dcy_0.0.77_darwin_arm64.tar.gz"
      sha256 "25c5b8e7316f1c0427427c32a81c3d93d9140688b7f714758ae76181a5c53984"

      define_method(:install) do
        bin.install "dcy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dcycle-by-WUM/dcy-releases/releases/download/v0.0.77/dcy_0.0.77_linux_amd64.tar.gz"
      sha256 "6785752db95a50e2958db1aa15f49771df3a5d60fb469efbc8777c1b350463df"
      define_method(:install) do
        bin.install "dcy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dcycle-by-WUM/dcy-releases/releases/download/v0.0.77/dcy_0.0.77_linux_arm64.tar.gz"
      sha256 "92d5f8a43cd53431e155dfb871d37715545fccd0e858352eaa982e112646ed9b"
      define_method(:install) do
        bin.install "dcy"
      end
    end
  end
end
