# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dcy < Formula
  desc "Dcycle CLI"
  homepage "https://github.com/Dcycle-by-WUM/dcycle-backend-app/tree/main/dc-go"
  version "0.0.98"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dcycle-by-WUM/dcy-releases/releases/download/v0.0.98/dcy_0.0.98_darwin_amd64.tar.gz"
      sha256 "20d1e7aa3951e2d1c17aea200af4d8be4e84f9ee5503811048b950cc8115d353"

      define_method(:install) do
        bin.install "dcy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dcycle-by-WUM/dcy-releases/releases/download/v0.0.98/dcy_0.0.98_darwin_arm64.tar.gz"
      sha256 "7a109ad5684a294430633a0a895b42bb79bb1822b4a1f89185ae29d342c27752"

      define_method(:install) do
        bin.install "dcy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dcycle-by-WUM/dcy-releases/releases/download/v0.0.98/dcy_0.0.98_linux_amd64.tar.gz"
      sha256 "1083192ca0b85d80beac30bd09e901a62ae7c77316f1eea09862fa0ed2870069"
      define_method(:install) do
        bin.install "dcy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dcycle-by-WUM/dcy-releases/releases/download/v0.0.98/dcy_0.0.98_linux_arm64.tar.gz"
      sha256 "b1669a6246b053d5c0b1fe8b695527a00f05ea039d11d2635c367469bd7e6181"
      define_method(:install) do
        bin.install "dcy"
      end
    end
  end
end
